const path = require('path');
const fs = require('fs');
const { execFileSync } = require('child_process');
const mongoose = require('mongoose');
const Analysis = require('../models/Analysis');
const aiClient = require('../services/aiClient');

/**
 * Handle new video upload & AI analysis pipeline
 */
const createAnalysis = async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        success: false,
        error: 'No video file uploaded. Please select a valid video file.'
      });
    }

    const videoFile = req.file;
    console.log(`[Analysis Controller] Received upload: ${videoFile.originalname} (${(videoFile.size / (1024 * 1024)).toFixed(2)} MB)`);

    // Forward video to FastAPI service
    let aiResult;
    try {
      aiResult = await aiClient.analyzeVideo(videoFile.path, videoFile.originalname);
    } catch (aiError) {
      console.error(`[Analysis Controller] AI Service Error: ${aiError.message}`);
      return res.status(502).json({
        success: false,
        error: `AI Service Error: ${aiError.message}. Make sure FastAPI is running on port 8000.`
      });
    }

    // Mirror heatmap to server/uploads/heatmaps if generated by ai-service
    let serverHeatmapUrl = '';
    if (aiResult.heatmap) {
      const aiOutputDir = path.join(__dirname, '../../../ai-service/outputs', aiResult.heatmap);
      const serverHeatmapDir = path.join(__dirname, '../../uploads/heatmaps');
      const targetHeatmapPath = path.join(serverHeatmapDir, aiResult.heatmap);

      if (fs.existsSync(aiOutputDir)) {
        try {
          fs.copyFileSync(aiOutputDir, targetHeatmapPath);
          serverHeatmapUrl = `/uploads/heatmaps/${aiResult.heatmap}`;
        } catch (copyErr) {
          console.warn('[Analysis Controller] Could not copy heatmap file, falling back:', copyErr.message);
          serverHeatmapUrl = `http://localhost:8000/outputs/${aiResult.heatmap}`;
        }
      } else {
        serverHeatmapUrl = `http://localhost:8000/outputs/${aiResult.heatmap}`;
      }
    }

    // Copy analyzed video if available in ai-service outputs
    let serverAnalyzedVideoUrl = `/uploads/videos/${videoFile.filename}`;

if (aiResult.analyzed_video) {
  const aiAnalyzedPath = path.join(
    __dirname,
    '../../../ai-service/outputs',
    aiResult.analyzed_video
  );

  const serverAnalyzedDir = path.join(
    __dirname,
    '../../uploads/analyzed'
  );

  const originalName = path.basename(aiResult.analyzed_video);
  const h264Name = originalName.replace(
    /\.mp4$/i,
    '_h264.mp4'
  );

  const targetAnalyzedPath = path.join(
    serverAnalyzedDir,
    h264Name
  );

  if (fs.existsSync(aiAnalyzedPath)) {
    try {
      execFileSync('C:\\Users\\kille\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-9.0.2-full_build\\bin\\ffmpeg.exe', [
        '-y',
        '-i',
        aiAnalyzedPath,
        '-c:v',
        'libx264',
        '-preset',
        'medium',
        '-crf',
        '23',
        '-pix_fmt',
        'yuv420p',
        '-c:a',
        'aac',
        targetAnalyzedPath
      ]);

      serverAnalyzedVideoUrl =
        `/uploads/analyzed/${h264Name}`;

      console.log(
        `[FFmpeg] Browser-compatible video created: ${targetAnalyzedPath}`
      );

    } catch (ffmpegErr) {
      console.error(
        '[FFmpeg] Video conversion failed:',
        ffmpegErr.message
      );

      serverAnalyzedVideoUrl =
        `/uploads/videos/${videoFile.filename}`;
    }
  }
}

    // Prepare tracked objects
    const mappedTrackedObjects = (aiResult.tracked_objects || []).map(item => ({
      track_id: item.track_id,
      team: item.constructor || item.team || 'Unknown',
      constructor_name: item.constructor || item.team || 'Unknown',
      frames_detected: item.frames_detected || 0,
      confidence: item.confidence || 0,
      first_detected: item.first_detected || '00:00',
      last_detected: item.last_detected || '00:00'
    }));

    // Prepare analysis document for MongoDB
    const newAnalysisData = {
      videoName: videoFile.originalname,
      originalFilename: videoFile.filename,
      status: aiResult.status || 'completed',
      duration: aiResult.video?.duration || 0,
      totalDetections: aiResult.statistics?.total_detections || 0,
      totalCars: aiResult.statistics?.total_cars || 0,
      totalEvents: aiResult.statistics?.total_events || 0,
      averageConfidence: aiResult.statistics?.average_confidence || 0,
      framesProcessed: aiResult.video?.frames_processed || aiResult.statistics?.frames_processed || 0,
      statistics: aiResult.statistics || {},
      constructors: aiResult.constructors || [],
      trackedObjects: mappedTrackedObjects,
      events: aiResult.events || [],
      timeline: aiResult.timeline || [],
      heatmapPath: serverHeatmapUrl,
      analyzedVideoPath: serverAnalyzedVideoUrl,
      originalVideoPath: `/uploads/videos/${videoFile.filename}`,
      fileSize: videoFile.size
    };

    // Save in MongoDB
    const savedAnalysis = await Analysis.create(newAnalysisData);
    console.log(`[Analysis Controller] Saved analysis record #${savedAnalysis._id} to MongoDB`);

    return res.status(201).json({
      success: true,
      message: 'Video successfully analyzed',
      data: savedAnalysis
    });

  } catch (error) {
    console.error(`[Analysis Controller] Internal server error: ${error.message}`);
    return res.status(500).json({
      success: false,
      error: `Server processing failed: ${error.message}`
    });
  }
};

/**
 * Get all analyses (history)
 */
const getAllAnalyses = async (req, res) => {
  try {
    const analyses = await Analysis.find().sort({ createdAt: -1 });
    return res.json({
      success: true,
      count: analyses.length,
      data: analyses
    });
  } catch (error) {
    console.error(`[Analysis Controller] Error fetching analyses: ${error.message}`);
    return res.status(500).json({
      success: false,
      error: `Failed to fetch analyses: ${error.message}`
    });
  }
};

/**
 * Get single analysis by ID
 */
const getAnalysisById = async (req, res) => {
  try {
    const { id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid Analysis ID format'
      });
    }

    const analysis = await Analysis.findById(id);

    if (!analysis) {
      return res.status(404).json({
        success: false,
        error: 'Analysis not found'
      });
    }

    return res.json({
      success: true,
      data: analysis
    });
  } catch (error) {
    console.error(`[Analysis Controller] Error fetching analysis #${req.params.id}: ${error.message}`);
    return res.status(500).json({
      success: false,
      error: `Failed to fetch analysis: ${error.message}`
    });
  }
};

/**
 * Delete analysis by ID
 */
const deleteAnalysis = async (req, res) => {
  try {
    const { id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid Analysis ID format'
      });
    }

    const analysis = await Analysis.findById(id);
    if (!analysis) {
      return res.status(404).json({
        success: false,
        error: 'Analysis record not found'
      });
    }

    await Analysis.findByIdAndDelete(id);

    // Optionally cleanup raw video files
    if (analysis.originalFilename) {
      const rawVideoPath = path.join(__dirname, '../../uploads/videos', analysis.originalFilename);
      if (fs.existsSync(rawVideoPath)) {
        try {
          fs.unlinkSync(rawVideoPath);
        } catch (e) {
          // ignore cleanup error
        }
      }
    }

    return res.json({
      success: true,
      message: 'Analysis deleted successfully'
    });
  } catch (error) {
    console.error(`[Analysis Controller] Error deleting analysis #${req.params.id}: ${error.message}`);
    return res.status(500).json({
      success: false,
      error: `Failed to delete analysis: ${error.message}`
    });
  }
};

/**
 * System health endpoint
 */
const getHealth = async (req, res) => {
  const mongoStatus = mongoose.connection.readyState === 1 ? 'connected' : 'disconnected';
  const aiHealth = await aiClient.checkAiHealth();
  const aiConfig = await aiClient.getAiConfig();

  return res.json({
    status: 'ok',
    server: 'running',
    timestamp: new Date().toISOString(),
    database: {
      status: mongoStatus,
      name: mongoose.connection.name || 'f1_race_analyzer'
    },
    aiService: {
      status: aiHealth.online ? 'online' : 'offline',
      mock_mode: aiConfig.mock_mode ?? true,
      details: aiHealth.data || null,
      error: aiHealth.error || null
    }
  });
};

module.exports = {
  createAnalysis,
  getAllAnalyses,
  getAnalysisById,
  deleteAnalysis,
  getHealth
};
